apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scavange-eventstore
spec:
  schedule: "0 4 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scavange-eventstore
            image: alpine
            args:
            - /bin/sh
            - -c
            - apk --no-cache add curl;
              curl -i -d {} -X POST eventstore-cluster:2113/admin/scavenge -u "admin:changeit"
          restartPolicy: OnFailure
